export const darkGray = '#222'
export const gray = '#666'
export const lightGray = '#ddd'
export const white = '#fff'
export const red = '#6d0404'
export const lightTeal = '#d2fbf5'
export const teal = '#00709e'